### ISSUE TITLE
ver.1.0.0을 위한 작업 환경을 구축한다.

### ISSUE THREAD

**Issue by 4BFC** [p-factory/P-factory-Front#63]
## ⚠️Issue
- ver.1.0.0을 위한 작업 환경을 구축한다.
> 현재 mono-repo를 node_modules 방식으로 설정 했다. pnp 방식도 있지만 우리가 설정한 라이브러리, 패키지들을 더 명료하게 확인하기 위해서 우선은 host를 node_modules방식으로 두었다.

## 🔗Link
- 🔗[React-Native Tailwind](https://enfp-jake.tistory.com/261)

## ✏️Task
- [x] pnpm으로 패키지메니저를 설치한다.
- [x] vite@3.2.0 환경에서 React-ts(swc)를 설치한다.
- [x] eslint와 prettier를 설치한다.
  - [x] prettier 확인
  - [x] eslint 확인
  - [x] plugin 동작 확인
    - [x] eslint-plugin-prefer-arrow 활성화
    - [x] eslint-plugin-import 비활성화
    - [x] eslint-config-prettier 활성화
    - [x] eslint-plugin-jsx-a11y 비활성화
    - [x] eslint-import-resolver-typescript 활성화
> `eslint-plugin~`은 plugin 배열에서 확인, `eslint-config~`은 extends 배열에서 확인
> eslint-import-resolver-typescript는 .eslintrc에서 `settings.import.resolver`로 확인
- [x] root/Recoil을 설치한다.
- [x] root/scss를 설치한다.
- [x] root/tanstackquery 설치한다.
- [x] React-Naitve를 설치한다.
- [x] pnpm으로 mono-repo를 구현한다.
- ~[ ] img를 public 페이지에서 관리할 수 있도록 구현~

## 📝Note
Pretteir 규칙은 eslint에서 관리하고 이와 관련된 메세지를 출력하게 한다.

## 🗓Next Task
- pnp 방식으로 전활할지 논의 필요
- 자동완성 확인 필요 - 1차 확인 완료
- TypeScript 규칙 적용 및 추가 필요 - 적용 완료
- shared의 alias를 사용할지 논의 필요
  - front 적용
  - app 미적용
- Husky Lib 적용 논의 필요
