### ISSUE TITLE
전체 레이아웃 디자인 시스템을 적용한다.

### ISSUE THREAD

**Issue by 4BFC** [p-factory/P-factory-Front#67]
## ⚠️Issue
- index.scss에 전체 레이아웃 디자인 시스템을 적용한다.

## ✏️Task
- [x]  index.scss에 전체 레이아웃 디자인 시스템을 적용한다.
  - [x] index.scss의 중앙 정렬 선택을 flex로 할지 margin auto로 작업을 할지 고민한다.
  - [x] max와 min의 차이를 명확히 구분한다.

## 🗓Next Task
- #65
